#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
生成用于相机标定的棋盘格（精确毫米尺寸）的可打印 SVG 文件。

默认参数：
- 纸张：A4 横向（297 x 210 mm）
- 棋盘：6 x 5 个方格（对应 5 x 4 内角点）
- 单格边长：40 mm
- 居中布局，四周边距自动适配

使用示例：
  python3 generate_chessboard.py

自定义示例（5x4 内角点 → 6x5 方格，单格 40mm，A4 横向）：
  python3 generate_chessboard.py \
    --squares-x 6 --squares-y 5 --square-size-mm 40 \
    --page A4 --orientation landscape --output chessboard_6x5_40mm.svg

打印建议：
- 使用激光打印机与哑光纸，打印时关闭“缩放/适应页面/边距自动调整”。
- 打印后用卡尺测量单格实际边长，作为 square_size（mm）。
- 将纸张平整贴到硬质平板，避免弯曲；不要覆亮膜以防反光。
"""

from __future__ import annotations

import argparse
import math
from typing import Tuple


A4_MM: Tuple[float, float] = (210.0, 297.0)  # (短边, 长边)
LETTER_MM: Tuple[float, float] = (215.9, 279.4)


def page_size_mm(name: str) -> Tuple[float, float]:
    key = name.lower()
    if key == "a4":
        return A4_MM
    if key in ("letter", "us-letter", "us_letter"):
        return LETTER_MM
    raise ValueError(f"不支持的纸张类型: {name}")


def build_svg(
    page_w_mm: float,
    page_h_mm: float,
    squares_x: int,
    squares_y: int,
    square_size_mm: float,
    margin_mm: float | None,
    black_first: bool = True,
    draw_border: bool = True,
    border_stroke_mm: float = 0.5,
    label_text: str | None = None,
) -> str:
    # 自动边距：若未指定，则使棋盘整体在页面上居中
    board_w = squares_x * square_size_mm
    board_h = squares_y * square_size_mm
    if margin_mm is None:
        margin_x = max(0.0, (page_w_mm - board_w) / 2.0)
        margin_y = max(0.0, (page_h_mm - board_h) / 2.0)
    else:
        margin_x = margin_y = margin_mm

    # 校验能否放下
    if board_w + 2 * margin_x - 1e-6 > page_w_mm or board_h + 2 * margin_y - 1e-6 > page_h_mm:
        raise ValueError(
            "棋盘尺寸与边距超过页面大小，请减小方格、方格数或边距，或改用更大纸张。"
        )

    # SVG 使用 mm 为单位
    svg_w = page_w_mm
    svg_h = page_h_mm

    # 左上角起点（SVG y 轴向下）
    origin_x = margin_x
    origin_y = margin_y

    def rect(x: float, y: float, w: float, h: float, fill: str, stroke: str = "none") -> str:
        return (
            f'<rect x="{x:.3f}" y="{y:.3f}" width="{w:.3f}" height="{h:.3f}" '
            f'fill="{fill}" stroke="{stroke}"/>'
        )

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{svg_w:.3f}mm" height="{svg_h:.3f}mm" viewBox="0 0 {svg_w:.3f} {svg_h:.3f}">',
        '<desc>Calibration chessboard generated by generate_chessboard.py</desc>',
        # 背景白
        rect(0, 0, svg_w, svg_h, fill="#ffffff"),
    ]

    # 绘制方格
    for j in range(squares_y):
        for i in range(squares_x):
            is_black = ((i + j) % 2 == 0) if black_first else ((i + j) % 2 == 1)
            fill_color = "#000000" if is_black else "#ffffff"
            x = origin_x + i * square_size_mm
            y = origin_y + j * square_size_mm
            parts.append(rect(x, y, square_size_mm, square_size_mm, fill=fill_color))

    # 棋盘外边框（可选）
    if draw_border:
        parts.append(
            f'<rect x="{origin_x:.3f}" y="{origin_y:.3f}" width="{board_w:.3f}" height="{board_h:.3f}" '
            f'fill="none" stroke="#000000" stroke-width="{border_stroke_mm:.3f}"/>'
        )

    # 角落标注（便于打印前核对）
    if label_text:
        # 使用简易文本，单位 mm；不同打印机可能会有极小偏差
        safe_x = origin_x + 1.5
        safe_y = origin_y + board_h + 6.0
        parts.append(
            f'<text x="{safe_x:.3f}" y="{safe_y:.3f}" font-family="Arial, Helvetica, sans-serif" '
            f'font-size="4" fill="#000000">{label_text}</text>'
        )

    parts.append("</svg>")
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description="生成用于标定的棋盘格 SVG 文件（毫米精度）")
    parser.add_argument("--squares-x", type=int, default=6, help="水平方格数（注意：内角点=方格数-1）")
    parser.add_argument("--squares-y", type=int, default=5, help="垂直方格数（注意：内角点=方格数-1）")
    parser.add_argument("--square-size-mm", type=float, default=40.0, help="单个方格边长（毫米）")
    parser.add_argument("--page", type=str, default="A4", choices=["A4", "Letter"], help="纸张尺寸")
    parser.add_argument(
        "--orientation",
        type=str,
        default="landscape",
        choices=["landscape", "portrait"],
        help="页面方向",
    )
    parser.add_argument("--margin-mm", type=float, default=None, help="页面统一边距（毫米），不填则自动居中")
    parser.add_argument("--no-border", action="store_true", help="不绘制棋盘外边框")
    parser.add_argument(
        "--white-first",
        action="store_true",
        help="左上角从白色开始（默认左上角为黑色）",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="./data/chessboard_A4_6x5_40mm_landscape.svg",
        help="输出文件名（.svg），默认保存到当前目录的data文件夹下",
    )

    args = parser.parse_args()

    page_w, page_h = page_size_mm(args.page)
    if args.orientation == "landscape":
        page_w, page_h = (max(page_w, page_h), min(page_w, page_h))
    else:
        page_w, page_h = (min(page_w, page_h), max(page_w, page_h))

    label = (
        f"{args.page} {args.orientation} | {args.squares_x}x{args.squares_y} squares | "
        f"{args.square_size_mm:.1f} mm | inner corners: {args.squares_x-1}x{args.squares_y-1}"
    )

    svg = build_svg(
        page_w_mm=page_w,
        page_h_mm=page_h,
        squares_x=args.squares_x,
        squares_y=args.squares_y,
        square_size_mm=args.square_size_mm,
        margin_mm=args.margin_mm,
        black_first=not args.white_first,
        draw_border=not args.no_border,
        border_stroke_mm=0.5,
        label_text=label,
    )

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(svg)

    print(f"已生成: {args.output}")
    print("打印提示：请在打印对话框中关闭缩放/适应页面，保持 100% 大小。")


if __name__ == "__main__":
    main()


